@API_HostAddress = https://localhost:7031

### Realms
GET {{API_HostAddress}}/api/v1/general/realms
Accept: application/json

### Character Data
GET {{API_HostAddress}}/api/v1/general/charData?name=Rekami&realm=frostmourne&region=us
Accept: application/json
